services:
  web:
    build: .
    volumes:
      - .:/app
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      DOMAIN: ${DOMAIN}
      REDIS_URL: ${REDIS_URL}

    command: >
      sh -c "alembic upgrade head && fastapi run src --port 8000 --host 0.0.0.0 "

    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis
      # db:
      #   condition: service_healthy
      # redis:
      #   condition: service_healthy

    networks:
      - app-network

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookly
      POSTGRES_PASSWORD: testpass

    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   retries: 5
    #   start_period: 10s

    ports:
     - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network
  redis:
    image: redis:6

    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s

    ports:
     - "6379:6379"

    networks:
     - app-network

  celery:
    build: .

    command: celery -A src.celery_tasks.c_app worker --loglevel=INFO

    volumes:
      - .:/app

    depends_on:
      - redis

    environment:
      REDIS_URL: ${REDIS_URL}

    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge