name: Conventional Commits

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: katelynn79@ethereal.email           
          password: D4dCwy6bz9c4UQ1Gyy
          subject: Github Actions Convention Commits
          to: pthoffman@dons.usfca.edu
          from: paris
          body: PR failed